### ISSUE TITLE
Does Freeflux solve parallel labeling expeirments?

### ISSUE THREAD

**Issue by liaochen1988** [Chaowu88/freeflux#2]
I just installed freeflux and it works well with Python 3.10. Thank you for such an important contribution. I am wondering if freeflux can solve fluxes by combining data from different tracer experiments? For example, I have MDV measured in two experiments, one using 1,2-C13 glucose and the other using 1,6-C13 glucose. Can data from both experiments analyzed together? Thank you!

**Comment by Chaowu88** [comment]
Thank you for trying it out. Now FreeFlux only only supports single labeling experiments, but multiple labeled substrates can be used simultaneously.
