### ISSUE TITLE
Bug in _set_default_concentration_bounds

### ISSUE THREAD

**Issue by roland-redmount** [Chaowu88/freeflux#3]
Hi, thanks for putting together this package, great job!  We have been trying it out in [our lab](https://www.nilssonlab.se/) and it looks promising so far.

However, I ran a problem when using the `InstFitter` class to fit time-series data -- I noticed that calling `InstFitter.prepare` erases any concentration bounds in `InstFitter.model.concentrations_bounds`, such as bounds previously set with `InstFitter.set_concentration_bounds`.  I found that `prepare` calls `_set_default_concentration_bounds` which seems to have a bug at this line:

https://github.com/Chaowu88/freeflux/blob/301b559303c5c71bbed5a67d811bec912c22d5be/src/freeflux/analysis/inst_fit.py#L152

Apparently it's checking `model.net_fluxes_bounds` instead of `concentrations_bounds`.

I can submit PR with a bug fix if helpful, let me know.  Thanks!

**Comment by Chaowu88** [comment]
Thank you for trying out FreeFlux, Roland. The bug is now fixed.
